cgi: Replace mfscgiserv with lizardfs-cgiserver
This commit replaces the old mfscgiserv script and adds a new script
called lizardfs-cgiserver. The new script is almost a copy of the old
one, but some parts of code are removed. This is because the old script
includes a buggy code for service management, which can't be simply
removed without breaking backward compatibility. One of important bugs
is that such a server doesn't really require write access to any
directory, but the mfscgiserv needs it for creating its PID file. This
makes it impossible to run it as user 'nobody'.

The new script is a copy of the previous one, but:
* all the PID file management code is removed
* it doesn't have a daemon-like interface (start, stop, restart, ...);
  instead it just runs in foreground
* two small issues with the code are fixed to make it pass a test which
  uses pylint

This commit changes the implementation of init script for this service
on Debian and Ubuntu to the one prepared by Dmitry Smirnov
<onlyjob@member.fsf.org>.

The lizardfs-cgiserv.service file is also modified to use the new script
instead of the old one.

SysV scripts for CentOS/RHEL are temporarily left unchanged.

Tests are modified so that if a test uses CGI_SERVER=yes parameter for
setup_local_empty_lizardfs, the new implementation will be used.

The old mfscgiserv script should be marked as deprecated as soon as it
is no longer used by CentOS/RHEL SysV scripts.

Closes #214
Closes #215
Closes #219

Change-Id: I5df243867208526a187713c8b3ba272adead6b79

diff --git a/debian/lizardfs-cgiserv.init b/debian/lizardfs-cgiserv.init
--- a/debian/lizardfs-cgiserv.init
+++ b/debian/lizardfs-cgiserv.init
@@ -1,67 +1,79 @@
 #!/bin/sh
-
+#
 ### BEGIN INIT INFO
-# Provides:		lizardfs-cgiserv
-# Required-Start:	$network $remote_fs
-# Required-Stop:	$remote_fs
-# Default-Start:	2 3 4 5
-# Default-Stop:		0 1 6
-# Short-Description:	Start mfscgiserv at boot time
-# Description:		mfscgiserv provides HTTP server for LizardFS CGI monitor.
+# Provides: lizardfs-cgiserv
+# Required-Start: $local_fs $network $syslog $remote_fs
+# Required-Stop: $local_fs $syslog $remote_fs
+# Should-Start: $syslog
+# Should-Stop: $network $syslog
+# Default-Start: 2 3 4 5
+# Default-Stop: 0 1 6
+# Short-Description: Start up the lizardfs-cgiserv server daemon
+# Description:       LizardFS is a distributed, scalable, fault-tolerant and highly available file system.
+#                    This service starts up the LizardFS cgiserv server daemon.
 ### END INIT INFO
 
-PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
-DAEMON=/usr/sbin/mfscgiserv
-NAME=mfscgiserv
-DESC=lizardfs-cgiserv
+NAME=lizardfs-cgiserv
+EXEC=/usr/bin/python
+DAEMON=/usr/sbin/lizardfs-cgiserver
 LIZARDFSCGISERV_USER=nobody
 LIZARDFSCGISERV_GROUP=nogroup
+BIND_HOST=0.0.0.0
+BIND_PORT=9425
+ROOT_PATH=/usr/share/mfscgi
 
-test -e $DAEMON || exit 0
+# Exit if executable is not installed
+[ -x $DAEMON ] || exit 0
 
-# Include lizardfs-cgiserv defaults if available
+# Read configuration variable file if it is present
+DEFAULTS_FILE=/etc/default/${NAME}
+[ -r "$DEFAULTS_FILE" ] && . $DEFAULTS_FILE
+
+PIDF=/var/run/${NAME}.pid
+RETRY=TERM/30/KILL/5
+
+# Load the VERBOSE setting and other rcS variables
+[ -f /etc/default/rcS ] && . /etc/default/rcS
+
+# define LSB log_* functions.
 . /lib/lsb/init-functions
-LIZARDFSCGISERV_ENABLE=false
-LIZARDFSCGISERV_DEFAULTS_FILE=/etc/default/lizardfs-cgiserv
-if [ -s "$LIZARDFSCGISERV_DEFAULTS_FILE" ]; then
-    . "$LIZARDFSCGISERV_DEFAULTS_FILE"
-    case "x$LIZARDFSCGISERV_ENABLE" in
-        xtrue) ;;
-        xfalse)
-	    log_warning_msg "lizardfs-cgiserv not enabled in \"$LIZARDFSCGISERV_DEFAULTS_FILE\", exiting..."
-	    exit 0
-	    ;;
-        *)
-            log_failure_msg "value of LIZARDFSCGISERV_ENABLE must be either 'true' or 'false';"
-            log_failure_msg "not starting lizardfs-cgiserv."
-            exit 1
-            ;;
-    esac
-fi
-
-set -e
 
 case "$1" in
-	start)
-		echo "Starting $DESC:"
-		$DAEMON start
-		;;
-
-	stop)
-		echo "Stopping $DESC:"
-		$DAEMON stop
-		;;
-
-	force-reload|restart)
-		echo "Restarting $DESC:"
-		$DAEMON restart
-		;;
-
-	*)
-		N=/etc/init.d/$NAME
-		echo "Usage: $N {start|stop|restart|force-reload}" >&2
-		exit 1
-		;;
+    start)
+        if $0 status >>/dev/null; then
+            log_action_msg "$NAME is already running"
+            exit 0
+        fi
+        log_action_begin_msg "$NAME starting"
+        if R=$(start-stop-daemon --start --exec ${EXEC} --oknodo --pidfile ${PIDF} --make-pidfile \
+            --background --chuid ${LIZARDFSCGISERV_USER}:${LIZARDFSCGISERV_GROUP} \
+            -- $DAEMON -H ${BIND_HOST} -P ${BIND_PORT} -R ${ROOT_PATH} 2>&1);
+        then
+            log_action_end_msg 0 "$R"
+        else
+            log_action_end_msg 1 "$R"
+        fi
+    ;;
+    stop)
+        log_action_begin_msg "$NAME stopping"
+        if R=$(start-stop-daemon --stop --exec $EXEC --pidfile $PIDF --retry=$RETRY --quiet);
+        then
+            log_action_end_msg 0 "$R"
+        else
+            log_action_end_msg 1 "not running"
+        fi
+        rm -f "$PIDF"
+    ;;
+    force-reload|restart)
+        $0 stop
+        $0 start
+    ;;
+    status)
+        ## return status 0 if process is running.
+        status_of_proc -p "$PIDF" "$DAEMON" "$NAME"
+    ;;
+    *)
+        N=/etc/init.d/$NAME
+        echo "Usage: $N {start|stop|restart|force-reload|status}" >&2
+    ;;
 esac
-
-exit 0
